/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedQuotaRouteImport } from './routes/_authenticated/quota'
import { Route as AuthenticatedUploadsRouteImport } from './routes/_authenticated/uploads'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsOauthRouteImport } from './routes/_authenticated/settings.oauth'
import { Route as AuthenticatedSettingsPolicyRouteImport } from './routes/_authenticated/settings.policy'
import { Route as AuthenticatedSettingsProvidersRouteImport } from './routes/_authenticated/settings.providers'
import { Route as ApiPublicDriveDownloadRouteImport } from './routes/api/public/drive/download'
import { Route as ApiPublicOauthGoogleCallbackRouteImport } from './routes/api/public/oauth/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotaRoute = AuthenticatedQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadsRoute = AuthenticatedUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOauthRoute =
  AuthenticatedSettingsOauthRouteImport.update({
    id: '/settings/oauth',
    path: '/settings/oauth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPolicyRoute =
  AuthenticatedSettingsPolicyRouteImport.update({
    id: '/settings/policy',
    path: '/settings/policy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProvidersRoute =
  AuthenticatedSettingsProvidersRouteImport.update({
    id: '/settings/providers',
    path: '/settings/providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDriveDownloadRoute = ApiPublicDriveDownloadRouteImport.update({
  id: '/api/public/drive/download',
  path: '/api/public/drive/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthGoogleCallbackRoute =
  ApiPublicOauthGoogleCallbackRouteImport.update({
    id: '/api/public/oauth/google/callback',
    path: '/api/public/oauth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/quota': typeof AuthenticatedQuotaRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/settings/oauth': typeof AuthenticatedSettingsOauthRoute
  '/settings/policy': typeof AuthenticatedSettingsPolicyRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/drive/download': typeof ApiPublicDriveDownloadRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/quota': typeof AuthenticatedQuotaRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/settings/oauth': typeof AuthenticatedSettingsOauthRoute
  '/settings/policy': typeof AuthenticatedSettingsPolicyRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/drive/download': typeof ApiPublicDriveDownloadRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/quota': typeof AuthenticatedQuotaRoute
  '/_authenticated/uploads': typeof AuthenticatedUploadsRoute
  '/_authenticated/settings/oauth': typeof AuthenticatedSettingsOauthRoute
  '/_authenticated/settings/policy': typeof AuthenticatedSettingsPolicyRoute
  '/_authenticated/settings/providers': typeof AuthenticatedSettingsProvidersRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/drive/download': typeof ApiPublicDriveDownloadRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/files'
    | '/quota'
    | '/uploads'
    | '/settings/oauth'
    | '/settings/policy'
    | '/settings/providers'
    | '/settings/'
    | '/api/public/drive/download'
    | '/api/public/oauth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/files'
    | '/quota'
    | '/uploads'
    | '/settings/oauth'
    | '/settings/policy'
    | '/settings/providers'
    | '/settings'
    | '/api/public/drive/download'
    | '/api/public/oauth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/files'
    | '/_authenticated/quota'
    | '/_authenticated/uploads'
    | '/_authenticated/settings/oauth'
    | '/_authenticated/settings/policy'
    | '/_authenticated/settings/providers'
    | '/_authenticated/settings/'
    | '/api/public/drive/download'
    | '/api/public/oauth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicDriveDownloadRoute: typeof ApiPublicDriveDownloadRoute
  ApiPublicOauthGoogleCallbackRoute: typeof ApiPublicOauthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quota': {
      id: '/_authenticated/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof AuthenticatedQuotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uploads': {
      id: '/_authenticated/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AuthenticatedUploadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/oauth': {
      id: '/_authenticated/settings/oauth'
      path: '/settings/oauth'
      fullPath: '/settings/oauth'
      preLoaderRoute: typeof AuthenticatedSettingsOauthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/policy': {
      id: '/_authenticated/settings/policy'
      path: '/settings/policy'
      fullPath: '/settings/policy'
      preLoaderRoute: typeof AuthenticatedSettingsPolicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/providers': {
      id: '/_authenticated/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/drive/download': {
      id: '/api/public/drive/download'
      path: '/api/public/drive/download'
      fullPath: '/api/public/drive/download'
      preLoaderRoute: typeof ApiPublicDriveDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google/callback': {
      id: '/api/public/oauth/google/callback'
      path: '/api/public/oauth/google/callback'
      fullPath: '/api/public/oauth/google/callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedQuotaRoute: typeof AuthenticatedQuotaRoute
  AuthenticatedUploadsRoute: typeof AuthenticatedUploadsRoute
  AuthenticatedSettingsOauthRoute: typeof AuthenticatedSettingsOauthRoute
  AuthenticatedSettingsPolicyRoute: typeof AuthenticatedSettingsPolicyRoute
  AuthenticatedSettingsProvidersRoute: typeof AuthenticatedSettingsProvidersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedQuotaRoute: AuthenticatedQuotaRoute,
  AuthenticatedUploadsRoute: AuthenticatedUploadsRoute,
  AuthenticatedSettingsOauthRoute: AuthenticatedSettingsOauthRoute,
  AuthenticatedSettingsPolicyRoute: AuthenticatedSettingsPolicyRoute,
  AuthenticatedSettingsProvidersRoute: AuthenticatedSettingsProvidersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicDriveDownloadRoute: ApiPublicDriveDownloadRoute,
  ApiPublicOauthGoogleCallbackRoute: ApiPublicOauthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
